import { Inter } from 'next/font/google'
import React from 'react'

import RecoilContainer from '@/components/Container/recoilContainer'

import type { Metadata } from 'next'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <RecoilContainer>{children}</RecoilContainer>
      </body>
    </html>
  )
}
