name: Run pnpm db:push

on:
  push:
    branches:
      - main

jobs:
  database_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1' # Node.jsのバージョンを更新

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run db:push
        run: pnpm db:push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
